[project]
name = "whosthatpokemon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "anthropic>=1.4.0",
    "chromadb>=1.5.9",
    "cohere>=7.1.1",
    "httpx>=0.28.1",
    "numpy>=2.5.3",
    "pydantic-settings>=2.15.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
]
